set wrap
set number
set relativenumber
set autoindent
set nocompatible

set encoding=utf-8

"Vim display tab:(>----),space:(-)
set list
set listchars=tab:>-,trail:-

"Enable mouse support
set mouse=a
set backspace=2
set laststatus=2

"tab,space settings
set tabstop=4 " set the width of a TAB
set shiftwidth=4
set softtabstop=4 " set the number of columns for hitting a TAB key
set expandtab " Expand TABs to spaces　
set ruler

"search settings
"set ignorecase
set smartcase

"keeps the cursor in the middle of the page
set scrolloff=999

"set colortheme
colorscheme slate
set t_Co=256    "to enable 256 colors in vim
syntax on
filetype plugin on

"Add custom headers
autocmd bufnewfile *.py so $HOME/.vim/template/py.template

"------------------------------------------------------"
"set laststatus=2 "showstatusline
"set cursorline   "underscore

"config hjkl keys
set nowrap
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

"Configurations for gitgutter
"When you make a change to a file tracked by git, the diff markers appear
"automatically. The delay is governed by vim's update option
set updatetime=200

"vim-airline
"let g:airline#extensions#tabline#left_sep = '|'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_splits = 0
let g:airline#extensions#tabline#buffer_nr_show = 0


"hide all when editing
"excerpt from stackoverflow:
"http://stackoverflow.com/questions/2404879/in-vim-how-can-i-have-a-permenant-status-line-showing-me-the-name-of-the-curren
let s:hidden_all = 0
function! ToggleHiddenAll()
    if s:hidden_all  == 0
        let s:hidden_all = 1
        set noshowmode
        set noruler
        set laststatus=0
        set noshowcmd
    else
        let s:hidden_all = 0
        set showmode
        set ruler
        set laststatus=2
        set showcmd
    endif
endfunction
nnoremap <S-h> :call ToggleHiddenAll()<CR>
