set wrap
set number
set relativenumber
set autoindent
set nocompatible

set colorcolumn=120
set encoding=utf-8

"Vim display tab:(>----),space:(-)
set list
set listchars=tab:>-,trail:-

"Enable mouse support
set mouse=a
set backspace=2
set t_Co=256
set laststatus=2

"tab,space settings
set tabstop=4 " set the width of a TAB
set shiftwidth=4
set softtabstop=4 " set the number of columns for hitting a TAB key
set expandtab " Expand TABs to spaces　
set ruler

"search settings
"set ignorecase
set smartcase

"keeps the cursor in the middle of the page
set scrolloff=999

"set colortheme
colorscheme slate
syntax on
filetype plugin on

"Add custom headers
autocmd bufnewfile *.py so /home/maojinrui/.vim/template/py.template

"------------------------------------------------------"
"set laststatus=2 "showstatusline
"set cursorline   "underscore
"You-complete-me settings
"let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_autoclose_preview_window_after_insertion  = 1

set nowrap
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')

"Configurations for gitgutter
"When you make a change to a file tracked by git, the diff markers appear
"automatically. The delay is governed by vim's update option
set updatetime=200
