set nowrap
set number
set autoindent
set nocompatible
set cursorline

"Vim display tab:(>----),space:(-)
set list
set listchars=tab:>-,trail:-

"Enable mouse support
set mouse=a
set backspace=2

"tab,space settings
set tabstop=4 " set the width of a TAB
set shiftwidth=4
set softtabstop=4 " set the number of columns for hitting a TAB key
set expandtab " Expand TABs to spaces　

"search settings
set ignorecase
set smartcase

"keeps the cursor in the middle of the page
set scrolloff=999
set laststatus=2 "showstatusline

"set colortheme
colorscheme slate
syntax on
filetype plugin on

"You-complete-me settings
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion  = 1
